services:
  localstack:
    image: localstack/localstack:3.8.1
    container_name: cloud-log-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: cloud-log-backend
    ports:
      - "3001:3001"
    env_file:
      - .env.example
    environment:
      - AWS_ENDPOINT=http://localstack:4566
    depends_on:
      - localstack

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: cloud-log-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
